import type { DetailedBriefingInput } from '../types/aiBriefing'

/**
 * 서버 `POST /api/ai-briefing`(Claude) 연동용 요청 프롬프트.
 * 입력 JSON은 서버에서 그대로 해석 가능하게 직렬화한다.
 */
export function buildInvestmentMemoPrompt(input: DetailedBriefingInput): string {
  const payload = {
    ...input,
    news: input.news.slice(0, 14).map((n) => ({
      title: n.title,
      summary: n.summary,
      sentiment: n.sentiment,
      category: n.category,
      publishedAt: n.publishedAt,
      source: n.source,
    })),
  }

  return [
    '역할: 한국 주식 애널리스트 수준의 단기·중기 투자 메모를 작성합니다.',
    '언어: 한국어 존댓말(~습니다/입니다, 권고는 ~하시기 바랍니다 등)로 통일합니다. 숫자·퍼센트·원화·억 단위를 적극 사용합니다.',
    '최신 뉴스/증권사 리포트가 있으면 반드시 반영하고, 단순 제목 나열이 아니라 왜 주가에 중요한지(트리거 vs 펀더멘털)를 분리해 설명합니다.',
    '',
    '금지:',
    '- "긍정적입니다", "모멘텀이 있습니다"처럼 근거 없는 추상 표현만 쓰지 말 것.',
    '- 뉴스 제목만 나열하지 말 것(원인-결과·주가에 미친 의미를 문장으로).',
    '- 매수·매도를 단정하지 말 것. "~일 수 있다", "~여지가 있다" 등 가능성 표현.',
    '- BUY/HOLD/WATCH 같은 액션 단어를 전략 제목으로 사용하지 말 것.',
    '- 기사 요약이 아니라 "왜 주가가 움직였는지" 추론을 덧붙일 것.',
    '- 목표가/투자의견 수치가 입력에 없으면 모른다고 명시할 것.',
    '',
    '출력 JSON 스키마(키만, 순서 무관):',
    '{',
    '  "title": string,',
    '  "atAGlanceTitle": string,     // 한눈에 보기 첫 줄. 종목명 없이 12~20자 내외 상황요약',
    '  "atAGlanceStrategy": string,  // 한눈에 보기 둘째 줄. 14~24자 내외 전략 한 줄',
    '  "paragraphs": string[6],  // 아래 순서 고정',
    '  "keyPoints": string[],   // 4~7개, 숫자 포함 한 줄 팩트',
    '  "risks": string[],       // 2~5개, 구체적',
    '  "strategyComment": string, // 3개월 +15% 전략·손절·익절을 한 문단으로',
    '  "strategyPlan": {',
    '    "title": string,',
    '    "marketView": string,',
    '    "timingView": string,',
    '    "positioningView": string,',
    '    "riskView": string,',
    '    "strategyMemo": string,',
    '    "evidence": string[],',
    '    "confidence": number',
    '  },',
    '  "tone": "bullish" | "neutral" | "caution"',
    '}',
    '',
    'paragraphs[0] — 가격·차트: 현재가, 전일 대비 등락률, 장중 고저, 52주 신고가 여부(입력값 기준), 컨센서스 평균·최고 목표가와 평균·최고 대비 상승여력(%).',
    'paragraphs[1] — 최근 주가 트리거: 뉴스 1~2개를 원인-결과로 연결. 목표가 상향·실적·수주·정책·매크로가 있으면 반드시 언급.',
    'paragraphs[2] — 펀더멘털: Trailing/Forward PER, EPS 성장률(있으면), 컨센서스 밴드 해석.',
    'paragraphs[3] — 수급·리스크: 3일 외국인·기관·개인 순매수(원 또는 억 환산), RSI·ATR 이격 과열, 차익실현·컨센서스 초과 여부.',
    'paragraphs[4] — 카탈리스트: 향후 1~4주 내 주가 변화를 만들 수 있는 촉매(실적발표, 수주공시, 증설, 정책, 매크로 이벤트)를 1~2개 제시하고, 왜 중요한지 설명.',
    'paragraphs[5] — 전략: 최신 리포트/목표가 변화/실적 프리뷰/수급을 우선 근거로 현재 접근법을 설명. 내부 점수는 보조로만 사용.',
    'strategyPlan 작성 규칙: action 단어 금지. 왜 지금 해당 전략인지(시장 기대, 선반영 수준, 수급, 과열, 눌림 필요 여부)를 설명.',
    'strategyPlan.evidence는 입력 데이터에서 확인 가능한 항목만 사용(근거 없는 숫자 금지).',
    'atAGlanceTitle — 종목명/코드/괄호 금지. 예: "52주 최고가 갱신 구간", "수급 유입이 이어지는 구간".',
    'atAGlanceStrategy — "전략:" 접두어 없이 짧은 실행 문구. 예: "눌림 확인 후 분할 진입", "분할 익절 중심 대응".',
    '',
    '특수 문구(해당 시 paragraphs 또는 keyPoints에 반영):',
    '- 현재가 > 컨센서스 평균 목표가: "현재가는 컨센서스 평균 목표가를 이미 넘어선 상태라, 추가 상승은 실적 서프라이즈나 수급 모멘텀이 필요합니다."',
    '- 평균 목표가 대비 상승여력 <8%: "컨센서스 기준 상승여력은 크지 않아 단기 모멘텀 중심으로 봐야 합니다."',
    '- 8~15%: "1개월 +15% 목표 전략 기준으로는 목표 구간에 근접한 상승여력이 남아 있습니다."',
    '- ≥15%: "컨센서스 기준으로도 15% 이상 여력이 남아 있어 중기 기대감은 유지됩니다."',
    '- RSI≥75: "RSI가 75를 넘어서 단기 과열 부담이 있습니다."',
    '- ATR 이격≥3.5: "ATR 이격이 커진 상태라 추격매수보다는 눌림 확인이 유리합니다."',
    '',
    '입력 데이터(JSON):',
    JSON.stringify(payload, null, 0),
  ].join('\n')
}
